version: '3'
services:
  etcd1:
    image: "shanbumin/etcd:3.3.12"
    environment:
      ETCDCTL_API: 3
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd1'
      - '--data-dir=/etcd-data'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd1:2379'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--initial-advertise-peer-urls=http://etcd1:2380'   
      - '--initial-cluster-token=sbm775b8'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "12379:2379"
    volumes:
      - ./store/etcd1/data:/etcd-data
    working_dir: /etcd-data
    restart: always
  etcd2:
    image: "shanbumin/etcd:3.3.12"
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd2'
      - '--data-dir=/etcd-data'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd2:2379'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--initial-advertise-peer-urls=http://etcd2:2380'   
      - '--initial-cluster-token=sbm775b8'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "22379:2379"
    volumes:
      - ./store/etcd2/data:/etcd-data
    working_dir: /etcd-data
    restart: always
  etcd3:
    image: "shanbumin/etcd:3.3.12"
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd3'
      - '--data-dir=/etcd-data'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd3:2379'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--initial-advertise-peer-urls=http://etcd3:2380'   
      - '--initial-cluster-token=sbm775b8'
      - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "32379:2379"
    volumes:
      - ./store/etcd3/data:/etcd-data
    working_dir: /etcd-data
    restart: always