version: "3"
services:
  #php-nginx服务
  #本地端口:容器端口 因为我们是一个容器跑多个项目,所以容器内端口也不能相互冲突
  php-nginx:
    container_name: php-nginx
    image: shanbumin/php:7.1-nginx-alpine3.10
    ports:
      - 8000:80 #test
      - 8001:81 #rhca_multi_platform
      - 8002:82 #novel_friends
      - 8003:83   #mini_short_video_platform
      - 8004:84  #WeDemo
      - 8005:85  #new_typer_api
    volumes:
       - ./nginx/conf/conf.d:/etc/nginx/conf.d
       - ./wwwroot/:/var/www/
    working_dir: /var/www
    restart: always
    networks:
       moka:
         ipv4_address: 10.33.0.2
  #php-golang
  php-golang:
    container_name: php-golang
    image: shanbumin/php:7.1-go-alpine3.10
    command: ["/usr/sbin/crond","-f"]
    volumes:
      - $GOPATH:/go
      - ./wwwroot/:/var/www/:cached
    working_dir: /var/www
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.3
  #php cli模式
  php-cli:
    container_name: php-cli
    image: shanbumin/php:7.1-cli-alpine3.10
    #command: ["tail","-f","/dev/null"]
    command: ["/usr/sbin/crond","-f"]
    working_dir: /var/www
    volumes:
       - ./wwwroot/:/var/www/
    restart: always
    networks:
       moka:
         ipv4_address: 10.33.0.10
  #mysqld服务
  mysqld:
     container_name: mysql
     image: shanbumin/mysql:5.7-stretch
     ports:
       - 3306:3306
     volumes:
       - ./mysql/5.7/data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
     restart: always
     networks:
       moka:
         ipv4_address: 10.33.0.5
  #redis服务
  redis:
    container_name: redis
    image: shanbumin/redis:4.0-alpine3.8
    ports:
      - 6379:6379
    volumes:
      - ./redis/4.0/data:/data
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.110
  #elasticsearch服务
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.2
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/7.4.2/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.111
  #mongod服务
  mongod:
    container_name: mongo
    image: shanbumin/mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - ./mongo/3.4/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.112
  #kibana服务
  kibana:
    container_name: kibana
    image: kibana:7.4.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://10.33.0.111:9200
    depends_on:
      - elasticsearch
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.113
  #rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: shanbumin/rabbitmq:3.7-management-alpine3.8
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: node001
    volumes:
      - ./rabbitmq/3.7/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: EGALBOSXYONYFFPBFFLT
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.114
 #consul
  consul:
    container_name: consul
    image: consul:1.4.5
    command: ["agent","-server","-bootstrap-expect=1","-ui","-bind=0.0.0.0","-client=0.0.0.0"]
    ports:
      - "8500:8500"
      - "8600:8600"
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.115
 #etcd
  etcd:
    container_name: etcd
    image: shanbumin/etcd:3.3.12
    environment:
      ETCDCTL_API: 3
    command: ["/usr/local/bin/etcd","--listen-client-urls","http://0.0.0.0:2379","--advertise-client-urls","http://0.0.0.0:2379"]
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./etcd/3.3.12/data:/default.etcd
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.116
 #gogs
  gogs:
    container_name: gogs
    image: gogs/gogs:latest
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./gogs/data:/data
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.120
#自定义虚拟网络
networks:
  moka:
     driver: bridge
     ipam:
       config:
         - subnet: 10.33.0.0/16
