version: "3"
services:
  #php-nginx服务
  #本地端口:容器端口
  php-nginx:
    container_name: php-nginx
    image: shanbumin/php:7.1-nginx-alpine3.10
    ports:
      - 8000:80 #test
      - 8001:81 #rhca_multi_platform
      - 8002:82 #feeder_admin
      - 8003:83 #hawk_applet
      - 8004:84  #typer
      - 8005:85  #lighter_admin
      - 8006:86  #automation_admin
      - 8007:87  #lighter_informatization
      - 9001:9001 #rhca_api_platfom_yaf
    volumes:
       - ./nginx/conf/conf.d:/etc/nginx/conf.d
       - ./wwwroot/:/var/www/:cached
    working_dir: /var/www
    restart: always
    networks:
       moka:
         ipv4_address: 10.33.0.2
  #php cli模式
  php-cli:
    container_name: php-cli
    image: shanbumin/php:7.1-cli-alpine3.10
    #command: ["tail","-f","/dev/null"]
    command: ["/usr/sbin/crond","-f"]
    working_dir: /var/www
    volumes:
       - ./wwwroot/:/var/www/
    restart: always
    networks:
       moka:
         ipv4_address: 10.33.0.10
  #mysqld服务
  mysqld:
     container_name: mysql
     image: shanbumin/mysql:5.7-stretch
     ports:
       - 3306:3306
     volumes:
       - ./mysql/data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
     restart: always
     networks:
       moka:
         ipv4_address: 10.33.0.5
  #redis服务
  redis:
    container_name: redis
    image: shanbumin/redis:4.0-alpine3.8
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.110
  #mongod服务
  mongod:
    container_name: mongo
    image: shanbumin/mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.112
  #rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: shanbumin/rabbitmq:3.7-management-alpine3.8
    ports:
      - "15672:15672"
    hostname: node001
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: EGALBOSXYONYFFPBFFLT
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.114
 #etcd
  etcd:
    container_name: etcd
    image: shanbumin/etcd:3.3.12
    environment:
      ETCDCTL_API: 3
    command: ["/usr/local/bin/etcd","--listen-client-urls","http://0.0.0.0:2379","--advertise-client-urls","http://0.0.0.0:2379"]
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./etcd/data:/default.etcd
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.116
 #golang 采用mod管理依赖的时候可以挂载到容器中直接使用
  crontab-master:
    container_name: crontab-master
    image: shanbumin/php:7.1-go-alpine3.10
    command: ["/usr/sbin/crond","-f"]
    ports:
      - "7081:7080"
    volumes:
      - /Users/sansheng/go:/go
      - /Users/sansheng/gomod:/gomod
      - ./wwwroot/:/var/www/
      - ./golang/uuid/200/crontab.uuid:/usr/local/var/run/crontab.uuid
      - ./golang/uuid/200/crontab.uuid:/usr/local/var/run/onekeyload.uuid
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.200
  crontab-201:
    container_name: crontab-201
    image: shanbumin/php:7.1-go-alpine3.10
    command: ["/usr/sbin/crond","-f"]
    volumes:
      - /Users/sansheng/go:/go
      - ./wwwroot/:/var/www/
      - /Users/sansheng/gomod:/gomod
      - ./golang/uuid/201/crontab.uuid:/usr/local/var/run/crontab.uuid
      - ./golang/uuid/201/crontab.uuid:/usr/local/var/run/onekeyload.uuid
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.201
  crontab-202:
    container_name: crontab-202
    image: shanbumin/php:7.1-go-alpine3.10
    command: ["/usr/sbin/crond","-f"]
    volumes:
      - /Users/sansheng/go:/go
      - ./wwwroot/:/var/www/
      - /Users/sansheng/gomod:/gomod
      - ./golang/uuid/202/crontab.uuid:/usr/local/var/run/crontab.uuid
      - ./golang/uuid/202/crontab.uuid:/usr/local/var/run/onekeyload.uuid
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.202
  crontab-203:
    container_name: crontab-203
    image: shanbumin/php:7.1-go-alpine3.10
    command: ["/usr/sbin/crond","-f"]
    volumes:
      - /Users/sansheng/go:/go
      - ./wwwroot/:/var/www/
      - /Users/sansheng/gomod:/gomod
      - ./golang/uuid/203/crontab.uuid:/usr/local/var/run/crontab.uuid
      - ./golang/uuid/203/crontab.uuid:/usr/local/var/run/onekeyload.uuid
    restart: always
    networks:
      moka:
        ipv4_address: 10.33.0.203
#自定义虚拟网络
networks:
  moka:
     driver: bridge
     ipam:
       config:
         - subnet: 10.33.0.0/16
